name = "nozesfy"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output"

[[d1_databases]]
binding = "DB"
database_name = "nozesfy-db"
database_id = "11dad3e1-4fed-4be8-be4f-58b5411a7978"
